
server.port=${PORT:8080}
server.address=0.0.0.0


spring.datasource.url=jdbc:postgresql://postgres:zVMvqlHEmJzAJG1j@db.xbqpdlecsbcifqumclga.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=zVMvqlHEmJzAJG1j
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=interviewflux@gmail.com
spring.mail.password=iziqnqdilpwsjhbe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true