spring.datasource.url=jdbc:postgresql://localhost:5432/interviewflux1
spring.datasource.username=postgres
spring.datasource.password=harshitha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=interviewflux@gmail.com
spring.mail.password=iziqnqdilpwsjhbe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
